### ISSUE TITLE
[PC][SP]ローディングアニメーション追加

### ISSUE THREAD

**Issue by nakaj1man** [iemong/nakajiman#103]
### 設置場所
- TOP -> WORKS：遷移時
- TOP -> WORKS詳細：遷移時
- WORKS -> WORKS詳細：遷移時
- WORKS詳細 -> WORKS詳細：作品切り替え時

### アニメーション詳細
画面切り替えアニメーションの間に下記イメージのような `LOADING` を点滅表示させる。
また、画面切り替えアニメーションの背景色をグレーから白に変更。
<img width="1680" alt="スクリーンショット 2019-04-18 14 19 00" src="https://user-images.githubusercontent.com/20411997/56338622-ae3ab980-61e5-11e9-96a4-26dc5c76e418.png">

**Comment by nakaj1man** [comment]
関連issue #35

**Comment by nakaj1man** [comment]
アニメーションモック

**Comment by iemong** [comment]
1人日

**Comment by nakaj1man** [comment]
※上記アニメーションに加えてWORKS一覧のサムネイルを読み込むアニメーションも追加

## アニメーション1
PC: https://zpl.io/b6oYd4q
SP: https://zpl.io/Vq5RjYl

## アニメーション2
PC&SP: https://zpl.io/awxjo4g

**Comment by nakaj1man** [comment]
サムネ画像のディゾルブはホバー画像と同じイージング
ただし時間短め

**Comment by nakaj1man** [comment]
確認したのでクローズ
