### ISSUE TITLE
サイトの常時SSL化

### ISSUE THREAD

**Issue by nakaj1man** [iemong/nakajiman#124]
## 目的
- サイトを常時SSL化させる

## やること
XSERVERの設定で下記の対応を行う
https://www.xserver.ne.jp/manual/man_server_fullssl.php

**Comment by iemong** [comment]
@nakaj1man やりました

http://kenta-nakajima.com/ -> https://kenta-nakajima.com/ にリダイレクトされる

**Comment by nakaj1man** [comment]
確認したのでクローズします。
