### ISSUE TITLE
[SP]WORKSの最初のサムネがヘッダーに隠れてしまう

### ISSUE THREAD

**Issue by nakaj1man** [iemong/nakajiman#130]
- 追加したtransitionと関係ありそう

![image](https://user-images.githubusercontent.com/20411997/71779959-7556a500-2fff-11ea-8144-91804b8607fd.png)

**Comment by iemong** [comment]
transition-groupはデフォルトだとspanタグになるんだった

**Comment by nakaj1man** [comment]
確認したのでクローズ
