### ISSUE TITLE
contentfulで作品画像を差し替えたら無関係なHOMEのサムネ画像も変わってしまう

### ISSUE THREAD

**Issue by nakaj1man** [iemong/nakajiman#161]
## 概要
![image](https://user-images.githubusercontent.com/20411997/74023687-94bc6580-49e3-11ea-9c55-7ece6121f8eb.png)

**Comment by iemong** [comment]
ランダムに変わるのはOK

最初に読み込んでる画像が次に呼ばれる画像と被らないようにする。

**Comment by nakaj1man** [comment]
確認したのでクローズ
