### ISSUE TITLE
アニメーションまとめ

### ISSUE THREAD

**Issue by ghost** [iemong/nakajiman#35]
## 2/17までに実装
- [x] 三角ボタンホバー時
http://taotajima.jp/works/

- [x] 作品詳細ホバー時のインタラクション
https://www.aid-dcc.com/works/

- [x] 作品間切り替え
- [x] 作品詳細クリック時のインタラクション
https://www.details.co.jp/works/gymnast-colon/

- [x] WORKSタブホバー時にアンダーバーがスケールする
http://www.olouen.com/menu

- [x] 黒ボタンホバー時のインタラクション
https://www.carbonbeauty.com/

## 4月までに実装
- [x] ローディング2種類
  WORKS一覧読み込み / 横トランジション時の読み込み

- [x] WORKSタブをクリックするとサムネが下に崩れてから上がってくる
https://hajimewatanabe.jp/portfolio/beauty#filter=base

- [x] ブラウザバックのインタラクション
https://www.details.co.jp/works/

- [x] ハンバーガーホバー時
- [x] バツボタンホバー時
https://www.refletcommunication.com/en/spirit

**Comment by nakaj1man** [comment]
@shinnoske0727 
チェックボックスつけたので実装完了しているアニメーションにチェック入れてください

**Comment by nakaj1man** [comment]
@shinnoske0727 PCハンバーガーボタンのホバー実装がまだ終わってないです

**Comment by nakaj1man** [comment]
2/17までの実装確認済み

**Comment by nakaj1man** [comment]
4末までのアニメーションにローディング追加

**Comment by iemong** [comment]
> WORKSタブをクリックするとサムネが下に崩れてから上がってくる
これやった

**Comment by nakaj1man** [comment]
確認したのでクローズ
