### ISSUE TITLE
[PC][SP]CONTACTページ復活

### ISSUE THREAD

**Issue by nakaj1man** [iemong/nakajiman#66]
DisabledになっているページをEnabledにする

**Comment by shinnoske0727** [comment]
formの参考
http://guide.onamae-server.com/sd/4_18_30_65/

**Comment by iemong** [comment]
https://cloud.google.com/functions/docs/tutorials/sendgrid

**Comment by iemong** [comment]
contentfulからデータ取ってきて、firebaseでメールを送れるようにすると最高

**Comment by nakaj1man** [comment]
- [ ] マージンがずれている
- [ ] HOMEボタンはZEPLINに上げているassetを使ってください

![image](https://user-images.githubusercontent.com/20411997/75240410-a2f1ea80-5807-11ea-8bca-cda7a4aeb605.png)

**Comment by nakaj1man** [comment]
確認したのでクローズ
