### ISSUE TITLE
[PC]WORKS一覧をリキッドレイアウトにする

### ISSUE THREAD

**Issue by nakaj1man** [iemong/nakajiman#88]
現状ディスプレイの横幅に合わせてリサイズできてない
<img width="1119" alt="2019-03-04 16 54 17" src="https://user-images.githubusercontent.com/20411997/53719245-e473e200-3ea0-11e9-96ea-b0ca822de6de.png">

下記サイト参考
http://www.kyotaro.org/kyotaro-cinematograph

**Comment by shinnoske0727** [comment]
ラップトップで見たとき3

**Comment by nakaj1man** [comment]
`960px` 以上を3column表示にしてください

**Comment by nakaj1man** [comment]
1024px 未満になったら2columnになる

**Comment by nakaj1man** [comment]
960pxがブレイクポイントになっていない

**Comment by nakaj1man** [comment]
確認したのでクローズ
