### ISSUE TITLE
[PC][SP]HOME画面に最初に表示されるサムネ画像のロジックを変更

### ISSUE THREAD

**Issue by nakaj1man** [iemong/nakajiman#98]
- 背景が白い「Sail」のサムネが最初に表示されるのは見栄えが悪いので変更。
- 「How to use Zeplin」はなるべく表示させないでほしい。

PC: https://zpl.io/259d7Zj
SP: https://zpl.io/aX1g0Kx

**Comment by iemong** [comment]
> 背景が白い「Sail」のサムネが最初に表示されるのは見栄えが悪いので変更。

contentfulであげ直す

**Comment by iemong** [comment]
> 「How to use Zeplin」はなるべく表示させないでほしい。

contentfulで表示・非表示フラグを追加する。

**Comment by nakaj1man** [comment]
確認したのでクローズ
